version: '3.8'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway:latest
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports: 
      - "5258:80"
    networks:
      - proxybackend

  backendnotas:
    image: ${DOCKER_REGISTRY-}backendnotas:latest
    build:
      context: .
      dockerfile: ./services/BackendNotas/Dockerfile
    ports: 
      - "7061:80"
    networks:
      - proxybackend

  backendusuario:
    image: ${DOCKER_REGISTRY-}backendusuarios:latest
    build:
      context: .
      dockerfile: ./services1/BackendUsuario/Dockerfile
    ports: 
      - "7084:80"
    networks:
      - proxybackend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - proxybackend

networks:
  proxybackend:
    driver: bridge

volumes:
  mongodb_data:
